# Generated by Django 4.0.4 on 2022-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='login_details',
            name='email',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
