# Generated by Django 4.0.4 on 2022-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_remove_login_details_id_alter_login_details_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_courses',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=20)),
                ('chapters', models.CharField(max_length=20)),
                ('videos_list', models.CharField(max_length=20)),
                ('course_description', models.CharField(max_length=20)),
                ('FAQs', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_courses',
            fields=[
                ('Course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('deactivation_days_left', models.CharField(max_length=20)),
                ('course_release_date', models.CharField(max_length=20)),
            ],
        ),
    ]
