# Generated by Django 4.0.4 on 2022-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_all_courses_user_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_course',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('total_duration', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=20)),
                ('chapters_vls', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=20)),
                ('FAQs', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='all_courses',
        ),
    ]
