# Generated by Django 4.0.4 on 2022-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_courses',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('total_duration', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=20)),
                ('chapters_vls', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=20)),
                ('FAQs', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usr_courses',
            fields=[
                ('Course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('deactivation_days_left', models.CharField(max_length=20)),
                ('course_release_date', models.CharField(max_length=20)),
            ],
        ),
    ]
