# Generated by Django 4.0.4 on 2022-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_courses',
            old_name='id',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='all_courses',
            name='FAQs',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='all_courses',
            name='chapters_vls',
            field=models.TextField(max_length=100),
        ),
    ]
