# Generated by Django 4.0.4 on 2022-06-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0002_rename_id_all_courses_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_courses',
            old_name='course_id',
            new_name='id',
        ),
    ]
