# Generated by Django 4.0.4 on 2022-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0003_rename_course_id_all_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_courses',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
