# Generated by Django 4.0.4 on 2022-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0004_alter_all_courses_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizes',
            fields=[
                ('course_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('que_options', models.TextField(max_length=300)),
            ],
        ),
    ]
