# Generated by Django 4.0.4 on 2022-06-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0005_quizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usr_courses',
            new_name='usr_course',
        ),
        migrations.AlterField(
            model_name='quizes',
            name='que_options',
            field=models.TextField(max_length=500),
        ),
    ]
