# Generated by Django 4.0.4 on 2022-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0007_usr_course_minutes_completed_usr_course_minutes_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_courses',
            name='type',
            field=models.CharField(default='none', max_length=5),
        ),
    ]
