# Generated by Django 4.0.4 on 2022-06-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0008_all_courses_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_courses',
            old_name='id',
            new_name='Course_id',
        ),
        migrations.RenameField(
            model_name='all_courses',
            old_name='name',
            new_name='course_name',
        ),
    ]
