# Generated by Django 4.0.4 on 2022-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0009_rename_id_all_courses_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_course',
            name='minutes_Completed',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usr_course',
            name='minutes_left',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usr_course',
            name='percentage_completed',
            field=models.CharField(max_length=3),
        ),
    ]
