# Generated by Django 4.0.4 on 2022-06-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0010_alter_usr_course_minutes_completed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usr_course',
        ),
    ]
