# Generated by Django 4.0.4 on 2022-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0011_delete_usr_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_course',
            fields=[
                ('Course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('deactivation_days_left', models.CharField(max_length=20)),
                ('course_release_date', models.CharField(max_length=20)),
                ('percentage_completed', models.CharField(max_length=3)),
                ('minutes_Completed', models.CharField(max_length=3)),
                ('minutes_left', models.CharField(max_length=3)),
            ],
        ),
    ]
