# Generated by Django 4.0.4 on 2022-06-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0012_usr_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_course',
            name='minutes_Completed',
            field=models.PositiveSmallIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usr_course',
            name='minutes_left',
            field=models.PositiveSmallIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usr_course',
            name='percentage_completed',
            field=models.PositiveSmallIntegerField(max_length=3),
        ),
    ]
