# Generated by Django 4.0.4 on 2022-06-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepro', '0013_alter_usr_course_minutes_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_course',
            name='minutes_Completed',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usr_course',
            name='minutes_left',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usr_course',
            name='percentage_completed',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
